package uz.pdp.pdp_crmwithjwt.domain.entity.enums;

public enum RolePermission {
    STAFF_DELETE,
    STAFF_CREATE,
    STAFF_UPDATE,
    STAFF_READ,
    STAFF_ALL,

    STUDENT_DELETE,
    STUDENT_CREATE,
    STUDENT_UPDATE,
    STUDENT_READ,
    STUDENT_ALL,

    GROUP_DELETE,
    GROUP_CREATE,
    GROUP_UPDATE,
    GROUP_READ,
    GROUP_ALL,

    MODULE_DELETE,
    MODULE_CREATE,
    MODULE_UPDATE,
    MODULE_READ,
    MODULE_ALL,

    LESSON_DELETE,
    LESSON_CREATE,
    LESSON_UPDATE,
    LESSON_READ,
    LESSON_ALL,

    ATTENDANCE_DELETE,
    ATTENDANCE_CREATE,
    ATTENDANCE_UPDATE,
    ATTENDANCE_READ,
    ATTENDANCE_ALL,

    DEPARTMENT_DELETE,
    DEPARTMENT_CREATE,
    DEPARTMENT_UPDATE,
    DEPARTMENT_READ,
    DEPARTMENT_ALL,

//    DEPARTMENT_DELETE,
//    DEPARTMENT_CREATE,
//    DEPARTMENT_UPDATE,
//    DEPARTMENT_READ,
//    DEPARTMENT_ALL,


}
